doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '12.1'
        types:
            address_currency: Aleksbrgt\Balances\DoctrineType\AddressCurrencyEnumType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Balances:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Aleksbrgt\Balances\Entity'
                alias: Balances
