eight_points_guzzle:
    clients:
        blockchair:
            base_url: https://api.blockchair.com
        etherscan:
            base_url: https://api.etherscan.io/api
        cryptocompare:
            base_url: https://min-api.cryptocompare.com
